rdzcn/kidaroo

- app/controllers/providers_controller.rb
ProvidersController
Activities to be created through ActivitiesController so the model is ready for pundit
> Added ProvidersController

- app/controllers/bookings_controller.rb
- app/views/bookings/create.html.erb
- app/views/bookings/destroy.html.erb
- app/views/bookings/new.html.erb
- app/views/bookings/show.html.erb
- config/routes.rb
> Booking controller

- app/models/activity.rb
- app/models/booking.rb
- app/models/event.rb
- app/models/provider.rb
- app/models/review.rb
- app/models/user.rb
- db/migrate/20180226172648_remove_start_date_from_activities.rb
- db/migrate/20180226172737_remove_end_date_from_activities.rb
- db/migrate/20180226172847_create_events.rb
- db/migrate/20180226174200_remove_activity_id_from_bookings.rb
- db/migrate/20180226174253_add_event_to_bookings.rb
- db/schema.rb
migrate again new schema
anna send the new schema through slack
> new schema

- config/routes.rb
> Feat, changed routes

- app/controllers/user_controller.rb
- app/models/activity.rb
- app/views/activities/index.html.erb
- app/views/pages/home.html.erb
- db/migrate/20180227112120_remove_provider_from_activities.rb
- db/migrate/20180227112330_drop_table_providers.rb
- db/schema.rb
> new migration

- app/models/activity.rb
- app/models/provider.rb
> associations

- db/migrate/20180227115406_add_user_id_to_activities.rb
- db/schema.rb
> add user references to activities

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/pages/home.html.erb
- db/migrate/20180227111626_add_role_to_users.rb
- db/schema.rb
> user roles available: customer or provider

- config/routes.rb
Missing keyword end in routes file
> Missing keyword end routes

- app/controllers/user_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/users/dashboard.html.erb
- config/routes.rb
> user model

- app/models/user.rb
> user model again

- app/views/users/dashboard.html.erb
- app/views/users/edit.html.erb
- config/routes.rb
edit profile through dashboard without photo
> dashboard and edit profile

- app/views/shared/_navbar.html.erb
Changed the airbnb options from the navbar
> feat, deleted airbnb options from Navbar

- app/controllers/reviews_controller.rb
- app/views/activities/index.html.erb
- app/views/reviews/create.html.erb
- app/views/users/dashboard.html.erb
- config/routes.rb
> heragbasjfbdvasrf

- app/views/shared/_navbar.html.erb
> removed settings from dropdown-navbar

- app/assets/stylesheets/components/_card-grid.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_grid.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_map.scss
- app/assets/stylesheets/pages/_activities.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/activities/_activities_list.html.erb
- app/views/activities/index.html.erb
> added_css_grids_results_index

- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/_activities_list.html.erb
- app/views/activities/index.html.erb
- app/views/layouts/application.html.erb
> Feat, grid CSS

- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> Feat, avatar navbar

- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/_activities_list.html.erb
Added a pinpoint next to the location in the results page
> Feat, added pinpoint icon to location in the index results

- app/assets/stylesheets/pages/_activities.scss
> Feat, closing tag missing

- app/controllers/activities_controller.rb
Filters are working!!!
Thanks to Konstantinos :)
> feat, fixed filters

- app/views/activities/_activities_list.html.erb
- app/views/activities/index.html.erb
Added filter created by Konstantinos to not to show past events
> Feat, filter events to not to show past events

- app/views/shared/_navbar.html.erb
Small change, changed avatar picture
> Feat, changed avatar picture

- app/controllers/activities_controller.rb
Improved filters
Still not perfect but work better
> Feat, improved filters

- app/controllers/activities_controller.rb
- app/views/shared/_navbar.html.erb
- app/views/users/dashboard.html.erb
> filters fixed for activities

- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/_activities_list.html.erb
Added truncate to limit the numbers of characters to display
> Feat, added truncate to results index

- app/assets/stylesheets/pages/_activities.scss
Removed text decoration for the title in the results index
> Feat, deleted text decoration title

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_sweet_form.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/layouts/_application.scss
- app/views/pages/home.html.erb
- app/views/shared/_banner.html.erb
- app/views/shared/_footer.html.erb
yep, it doesnt move in a shitty way. it is proper responsive homepage
hell yeah mobile first
> feat: responsivness corrected

- app/views/activities/_activities_list.html.erb
> Feat, clickable cards

- app/assets/stylesheets/pages/_activities.scss
- app/views/activities/_activities_list.html.erb
Removed the text decoration in the card
> Cards without text deco

- app/views/activities/_activities_list.html.erb
Cards, clickable and without text decoration
Missing style
> Feat, final cards, missing style

- app/views/activities/_activities_list.html.erb
> Feat, cards again

- app/views/pages/home.html.erb
GM
I changed the location filter in the show page, to display more neighbourhoods
> Feat, changed and add location filters in homepage dropdown

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_buttons.scss
- app/views/pages/home.html.erb
- app/views/shared/_banner.html.erb
Button added on the homepage to go to the filters
> Feat, added button in the homepage to jump to the filters

- app/assets/stylesheets/components/_buttons.scss
Changed color of the button on the homepage
> Feat, changed color button in homepage

- app/views/users/dashboard.html.erb
> better dashboard - not ready yet

- app/assets/stylesheets/components/_sweet_form.scss
- app/assets/stylesheets/pages/_index.scss
- app/assets/stylesheets/pages/_payments-new.scss
- app/views/bookings/show.html.erb
- app/views/pages/home.html.erb
- app/views/payments/new.html.erb
> payments style

- app/views/pages/home.html.erb
Heroku displays yesterday's weather while local host displays today
Small trick done to display properly on Heroku
> Feat, changed weather API display Heroku

- app/controllers/activities_controller.rb
- app/views/pages/home.html.erb
Filters are working ....
If the provided by the user tag does not exist in our activities the filter ignores the input as it did not exist. If you guys want we can change that
> filters working

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_testimonial.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/pages/home.html.erb
- app/views/shared/_testimonial.html.erb
> Feat, added testiomial on homepage

- app/views/shared/_testimonial.html.erb
Removed button from testimonial
> Feat, removed button from testimonial

- app/views/shared/_testimonial.html.erb
Removed quotes from testimonial
> Feat, testimonial

- app/views/activities/new.html.erb
Added dropdown menu in the new form to match the filters
> Feat, added dropdowm menu new form

- app/controllers/activities_controller.rb
- app/views/activities/new.html.erb
- app/views/pages/home.html.erb
- db/migrate/20180305091215_add_district_to_activities.rb
- db/schema.rb
added district to activities....you have to migrate.....and we have to add the district to every view page
> Activities filters

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_share_button_social_media.scss
- app/views/shared/_share_button_social_media.html.erb
Added social media share button
Still needs to be render in the show activity page
> Feat, added social media share button

- app/controllers/activities_controller.rb
- app/views/activities/_activities_list.html.erb
Markers on the map to correspond to the events displayed
> Markers on index page

- app/assets/stylesheets/components/_testimonial.scss
- app/views/shared/_testimonial.html.erb
Customised testimonials, text and pictures
> Feat, customized testimonials, pictures and text

- app/controllers/activities_controller.rb
- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/activities/show.html.erb
> Authentication

- app/views/shared/_testimonial.html.erb
> Feat, added new testimonial

- app/views/shared/_testimonial.html.erb
Fixed little typo in testimonial
> Feat, corrected type in testimonial

- app/views/shared/_testimonial.html.erb
Changed interval of the carousel in the testimonial, now is slower
> Feat, changed the speed of the interval for the testimonials

- app/assets/stylesheets/pages/_activities_show.scss
- app/views/activities/show.html.erb
Moved the price from the description column and made a whole column in the show page
> Feat, added column for price in the show page

- app/assets/stylesheets/components/_calendar.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_weather.scss
- app/controllers/activities_controller.rb
- app/views/pages/home.html.erb
- app/views/shared/_banner.html.erb
- app/views/shared/_weather.html.erb
re-f*cking-designed 
love it or hate it but merge it
> make TA happpy

- app/models/activity.rb
- app/models/user.rb
> fix - rating

- app/views/layouts/application.html.erb
Added metadata
You just need few clicks to book an activity for your children in Berlin. Have a look at the categories and enjoy a day full of fun!
> Feat, added metadata

- app/views/activities/_activities_list.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_reviews_show.html.erb
Activities were repeating in the index page every time an event was added
Also added metadata at the end of the head
> Fixed index page as activities kept repeating

- app/views/activities/show.html.erb
Events in the past were still appearing
> Feat, events in the past are not displayed anymore

- app/assets/stylesheets/pages/_payments-new.scss
- app/views/payments/new.html.erb
Changed style and text of pay payments page
> Feat, changed text and style payments page

- app/assets/stylesheets/pages/_payments-new.scss
- app/views/bookings/show.html.erb
- app/views/payments/new.html.erb
Confirmation of the reservation with button to go to your dashboard
> Payments confirmation booking

- app/views/shared/_cards.html.erb
- app/views/shared/_reviews_show.html.erb
recomended activities and reviews changed because it crashed
> recomended activities

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_sweet_form.scss
Changed the color of the button on the banner to have the same color as the navbar and aligned the text
> Feat, changed button banner and aligned text

- app/assets/stylesheets/components/_navbar.scss
Reduced size of the navbar
Navbar 70px and img 65px
> Feat, reduced size os navbar and img

- app/assets/stylesheets/components/_testimonial.scss
Changed testimonials
background white
> Feat, changed style testimonials

- app/assets/stylesheets/components/_weather.scss
- app/views/shared/_weather.html.erb
Changed the border radius of the boxes in the recommended section
Also changed the size of the h1 from 46 to 40px
> Feat, changed border and h1size of recommended activities

- app/javascript/packs/map.js
- app/models/activity.rb
- app/models/message.rb
> snazzy maps

- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
> sign in form

- app/assets/stylesheets/components/_calendar.scss
- app/assets/stylesheets/components/_weather.scss
- app/views/shared/_weather.html.erb
> Weather boxes reduced

- app/views/users/_future_bookings.html.erb
> future events dashboard

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_matt-style.scss
- app/views/shared/_banner.html.erb
> Feat, changed font fammily form banner and removed underline

- app/assets/stylesheets/components/_reviews_show.scss
- app/views/users/_future_bookings.html.erb
- app/views/users/_past_bookings.html.erb
> no random rating any more please

- app/assets/stylesheets/components/_footer_stealed.scss
- app/assets/stylesheets/pages/_activities.scss
- app/controllers/activities_controller.rb
- app/views/activities/index.html.erb
- app/views/layouts/application.html.erb
stikiness with big thankyou to DIMITRI
> dimitri fix map

- app/views/shared/_cards.html.erb
> last 3 activities

- app/controllers/events_controller.rb
> chat_no_footer

- app/controllers/activities_controller.rb
- app/controllers/bookings_controller.rb
- app/controllers/reviews_controller.rb
- app/controllers/users_controller.rb
- app/models/activity.rb
- app/models/booking.rb
Hi, was looking for projects to contribute to and stumbled upon yours. Hope you don't mind these small refactoring I did.
> Small refactor
